### ISSUE TITLE
Default configuration file

### ISSUE THREAD

**Issue by mgxm** [andygrove/datafusion#74]
I wonder if we could write a simple configuration file.
A very simple .toml file that defines all the necessary configurations.
So when the project forwards and needs more some configurations it would be easier to use and we do not need to pass all the arguments every time.

For example:
```
# Here we can put some configuration that
# are common to both
[datafusion]
etcd = "http://127.0.0.1:2379"

[worker]
bind = "0.0.0.0:8080"
data_dir = "./path/data_dir"
webroot = "./src/bin/worker"

[console]
# some specific configuration
# to the console
```
When we initialize the console or the worker we could pass a flag that searches for the configuration.
 - will try to load the configuration from a default path
`worker -c`
- or we can pass the path to configuration file
`worker -c /path/to/config.toml`

And likewise for the console

**Comment by KenSuenobu** [comment]
I would almost vote that `-c (filename)` should be the requirement for this.  Having `-c` by itself stand to reason that this is a flag/toggle, and not a parameter.  I think this is a good idea as well.

**Comment by andygrove** [comment]
@mgxm I think this is a great idea. Let's do this for 0.4.0

**Comment by vladimir-lu** [comment]
I would like to see a system where no configuration files are used. Typically this is a fairly major issue with current systems like Hadoop/Spark - the configuration files are updated on one host and not on another, and then they need to be copied anyway because all nodes in the cluster are not the same.

Preferably, all configuration would like in a configuration service - etcd seems up for the task I think :) So the only parameter that datafusion needs would be the etcd hosts, and this could be provided via environment variable.
